language: java
install: true

jdk:
  - openjdk13

services:
  - docker

jobs:
  include:
    - stage: build
      script: ./gradlew -PuseInstalledNvm=true build
      if: tag IS blank
    - stage: deploy
      script: ./gradlew -PuseInstalledNvm=true  build publish && ./docker-ci.sh
      if: tag IS present
  
cache:
  directories:
  - artifacts
  - $HOME/.m2
  - .gradle
  - ui-client/.gradle/nodejs
  - ui-client/.gradle/npm
