language: java
install: true

jdk: 
  - openjdk11

services:
  - docker

jobs:
  include:
    - stage: build
      script: ./gradlew -Djavax.net.debug=ssl:handshake:verbose:keymanager:trustmanager -Djava.security.debug=access:stack -Djavax.net.ssl.trustStore=certificates/cacerts -Djavax.net.ssl.trustStorePassword=changeit -PuseInstalledNvm=true build
      if: tag IS blank
    - stage: deploy
      script: ./gradlew -Djavax.net.ssl.trustStore=certificates/cacerts -Djavax.net.ssl.trustStorePassword=changeit -PuseInstalledNvm=true build publish && ./docker-ci.sh
      if: tag IS present
  
cache:
  directories:
  - artifacts
  - $HOME/.m2
  - .gradle
  - ui-client/.gradle/nodejs
  - ui-client/.gradle/npm
