language: java
install: true

jdk: 
  - openjdk11

services:
  - docker

jobs:
  include:
    - stage: build
      script: ./gradlew -PuseInstalledNvm=true build
      if: tag IS blank
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - stage: deploy
      script: ./gradlew -Djavax.net.ssl.trustStore=certificates/cacerts -Djavax.net.ssl.trustStorePassword=changeit -PuseInstalledNvm=true build publish && ./docker-ci.sh
      if: tag IS present
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
  
cache:
  directories:
  - artifacts
  - $HOME/.m2
  - .gradle
  - ui-client/.gradle/nodejs
  - ui-client/.gradle/npm
