{
  "formatVersion": "1.1",
  "component": {
    "group": "org.modelix",
    "module": "model-api",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "pur5cny77zdotgsvkzxnfvbog4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "model-api-metadata-1.0-SNAPSHOT.jar",
          "url": "model-api-1.0-SNAPSHOT.jar",
          "size": 24750,
          "sha512": "4f7e2083ed82bd996bf4ade594eca6ca8d2ccb9b7f0e6a0040f1baa9f0b243eae7a44acaf9bb86271a3ec501df8537c6b8e7197e1b5addef9089ae6b5d71753a",
          "sha256": "7e1d32247856e909c9266f8b2564d83c08c1953894ec8fb3207739c65fe7f3da",
          "sha1": "48aa156a9d4370218b871878d0b08629539437ac",
          "md5": "8415cc6a380cf4d09480ea9120023736"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-api-js/1.0-SNAPSHOT/model-api-js-1.0-SNAPSHOT.module",
        "group": "org.modelix",
        "module": "model-api-js",
        "version": "1.0-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-api-js/1.0-SNAPSHOT/model-api-js-1.0-SNAPSHOT.module",
        "group": "org.modelix",
        "module": "model-api-js",
        "version": "1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-api-jvm/1.0-SNAPSHOT/model-api-jvm-1.0-SNAPSHOT.module",
        "group": "org.modelix",
        "module": "model-api-jvm",
        "version": "1.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-api-jvm/1.0-SNAPSHOT/model-api-jvm-1.0-SNAPSHOT.module",
        "group": "org.modelix",
        "module": "model-api-jvm",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
