{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-api/1.0-SNAPSHOT/model-api-1.0-SNAPSHOT.module",
    "group": "org.modelix",
    "module": "model-api",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "pur5cny77zdotgsvkzxnfvbog4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "model-api-jvm-1.0-SNAPSHOT.jar",
          "url": "model-api-jvm-1.0-SNAPSHOT.jar",
          "size": 108947,
          "sha512": "1579dcf39c7c3039d6d0cfcfc86c4b1c5ae718a08b025ed3b65e6ed8a1dd9babad316ae0f7443749a5456598b378985e818586381cd93aeddcbfcc811b95a0b7",
          "sha256": "a9f0a7b46c2698d1dc22552598248f69520ebdb6642722faea7c84154ae85e7c",
          "sha1": "2ed6580927ae604adecf4fb596c0628cb4adbb01",
          "md5": "3c18010bf18a1ca2ffc39e6bdb125ae7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "log4j",
          "module": "log4j",
          "version": {
            "requires": "1.2.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.31"
          }
        }
      ],
      "files": [
        {
          "name": "model-api-jvm-1.0-SNAPSHOT.jar",
          "url": "model-api-jvm-1.0-SNAPSHOT.jar",
          "size": 108947,
          "sha512": "1579dcf39c7c3039d6d0cfcfc86c4b1c5ae718a08b025ed3b65e6ed8a1dd9babad316ae0f7443749a5456598b378985e818586381cd93aeddcbfcc811b95a0b7",
          "sha256": "a9f0a7b46c2698d1dc22552598248f69520ebdb6642722faea7c84154ae85e7c",
          "sha1": "2ed6580927ae604adecf4fb596c0628cb4adbb01",
          "md5": "3c18010bf18a1ca2ffc39e6bdb125ae7"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../model-api-metadata/1.0-SNAPSHOT/model-api-metadata-1.0-SNAPSHOT.module",
        "group": "org.modelix",
        "module": "model-api-metadata",
        "version": "1.0-SNAPSHOT"
      }
    }
  ]
}
