{
  "formatVersion": "1.1",
  "component": {
    "group": "org.modelix",
    "module": "model-api",
    "version": "2020.3.1710.8c5c648",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6",
      "buildId": "splibn6r3ze6leak4qllkltip4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "model-api-metadata-2020.3.1710.8c5c648.jar",
          "url": "model-api-2020.3.1710.8c5c648.jar",
          "size": 24750,
          "sha512": "32f8d71f7057c8b60b4cfc64c84eb09297c626ffafa871e9e4202527a49b8d90bd537700c697f74ed308b458a6176da1fca7ed7ef8cf5d10bdea581db728c5e6",
          "sha256": "809cca9fb2ec155c9df2504e4a44cfb7abc76d59402890c63c03a485d24c1008",
          "sha1": "4af01df3bda68a414702cbdff4d01919bb8d75a0",
          "md5": "c0b26fb829cee8416bed55f1e426a826"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-api-js/2020.3.1710.8c5c648/model-api-js-2020.3.1710.8c5c648.module",
        "group": "org.modelix",
        "module": "model-api-js",
        "version": "2020.3.1710.8c5c648"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../model-api-js/2020.3.1710.8c5c648/model-api-js-2020.3.1710.8c5c648.module",
        "group": "org.modelix",
        "module": "model-api-js",
        "version": "2020.3.1710.8c5c648"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-api-jvm/2020.3.1710.8c5c648/model-api-jvm-2020.3.1710.8c5c648.module",
        "group": "org.modelix",
        "module": "model-api-jvm",
        "version": "2020.3.1710.8c5c648"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../model-api-jvm/2020.3.1710.8c5c648/model-api-jvm-2020.3.1710.8c5c648.module",
        "group": "org.modelix",
        "module": "model-api-jvm",
        "version": "2020.3.1710.8c5c648"
      }
    }
  ]
}
