name: Integration Tests

on: [push]

jobs:
  runIntegrationTests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-runIntegrationTests-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-runIntegrationTests-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-runIntegrationTests-
          gradle-
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Integration Tests
      run: ./gradlew -i runIntegrationTests
