name: ModelServer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-model-server-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-model-server-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-model-server-
          gradle-
    - name: Assemble
      run: cd model-server && ../gradlew assemble

  unitTests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-model-server-unitTests-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-model-server-unitTests-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-model-server-unitTests-
          gradle-
    - name: Run unit tests
      run: cd model-server && ../gradlew test

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-model-server-lint-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-model-server-lint-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          gradle-model-server-lint-
          gradle-
    - name: Run linter
      run: cd model-server && ../gradlew spotlessCheck

  functionalTests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-model-server-functionalTests-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-model-server-functionalTests-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            gradle-model-server-functionalTests-
            gradle-
      - name: Run functional tests
        run: cd model-server && ../gradlew cucumber
